spring.application.name=Curso con Spring Boot
server.servlet.context-path=/sistema/api/v1
server.port=8081

service.products=list

# Configuración personalizada de la aplicación
app.name=Sistema de Productos
app.version=1.0.0
app.author=Sebastian Estrada
app.language=es
app.country=Colombia