spring.application.name=SpringSecurityApp
server.port = 8081


# DataBase configuration
#spring.datasource.hikari.connectionTimeout=20000
#spring.datasource.hikari.maximumPoolSize=5
spring.datasource.url=jdbc:postgresql://localhost:5432/securitydb
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Security Config
#spring.security.user.name=santiago
#spring.security.user.password=1234